[package]
name = "kubectl-whoami"
version = "0.1.0"
authors = ["Jiangge Zhang"]
edition = "2018"

[dependencies]
base64 = "0.11"
openssl = "0.10"
kube = "0.28.1"
k8s-openapi = { version = "0.7", default-features = false, features = ["v1_17"] }
tokio = { version = "0.2", features = ["full"] }
